// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenTrace(arg1) {
  return window['go']['main']['App']['OpenTrace'](arg1);
}

export function OpenTraceDialog() {
  return window['go']['main']['App']['OpenTraceDialog']();
}
