// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function OpenTrace(arg1:string):Promise<model.TraceSummary>;

export function OpenTraceDialog():Promise<model.TraceSummary>;
